### ISSUE TITLE
PCR policy and values do not seem to affect nvread

### ISSUE THREAD

**Issue by spmaniato** [01org/tpm2-tools#348]
Hello :slightly_smiling_face: 

I'm working with an Intel TPM 2.0 device in an embedded Linux environment. I have installed TPM2.0-TSS (`6e58f75`), tpm2-abrmd (`1003fcf`), and tpm2.0-tools (effc1fa).

I'm trying to set up secure boot based on a PCR policy. To this end, I want the TPM to prevent reading of a "secret" stored in its NV area when the value of a PCR (`09` in the example below) is not the one specified in the policy. However, it looks like I can read the secret regardless of the policy. Please see example below.

Here's the happy path, which I think works as expected:

```bash
$ dd if=/dev/urandom of="/tmp/secret.bin" bs=1 count=32
$ xxd -p /tmp/secret.bin 
24516beb6a0a9ac1366857b66435513d902817383fcbae7bb3e2dfed7ce8b799

$ tpm2_listpcrs -L 0x4:9 -o pcr_09.bin
$ xxd -p pcr_09.bin 
94a2cdb9512a9c288d1e21186f2f6ccbdd607d41

Bank/Algorithm: TPM_ALG_SHA1(0x0004)
PCR_09: 94 a2 cd b9 51 2a 9c 28 8d 1e 21 18 6f 2f 6c cb dd 60 7d 41

$ tpm2_createpolicy -P -i 9 -F pcr_09.bin -f policy.digest
$ xxd -p policy.digest 
65b786bb8a2edc6900d4b90ea6f20da30c3ea83da45a8c0fa323419c8f401f3e

$ tpm2_nvdefine -x 0x1500001 -a 0x40000001 -s 32 -t 0x2000A -r -L policy.digest -P <OWNER_PW>
$ tpm2_nvlist
1 NV indexes defined.

  0. NV Index: 0x1500001
  {
	Hash algorithm(nameAlg):11
 	The Index attributes(attributes):0xa0002
 	The size of the data area(dataSize):32
 	Authorization Policy for R/W/D: 65B786BB8A2EDC6900D4B90EA6F20DA30C3EA83DA45A8C0FA323419C8F401F3E
  }

$ tpm2_nvwrite -x 0x1500001 -a 0x40000001 -f /tmp/secret.bin -P <OWNER_PW>
$ tpm2_nvread -x 0x1500001 -a 0x40000001 -s 32 -o 0 -P <OWNER_PW>

The size of data:32
 24  51  6b  eb  6a  0a  9a  c1  36  68  57  b6  64  35  51  3d  90  28  17  38  3f  cb  ae  7b  b3  e2  df  ed  7c  e8  b7  99
```

So far so good. But now I'm gonna purposely modify the policy to one that is not met by PCR 09. Some cleanup first, just in case:

```bash
$ rm policy.digest
$ tpm2_nvrelease -x 0x1500001 -a 0x40000001 -P <OWNER_PW>
$ tpm2_nvlist
0 NV indexes defined.
```

Now I'm gonna handcraft a "wrong" policy:

```bash
$ dd if=/dev/urandom of="pcr_rand.bin" bs=1 count=20
$ xxd -p pcr_rand.bin 
be52323c7a57a50a50bd75f25c823f033e65229c
$ tpm2_createpolicy -P -i 9 -F pcr_rand.bin -f policy.digest # PCR 09 policy based on random values
$ xxd -p policy.digest 
bc3daed93da82ee5bb91193878cd9699659f6786fdf039722ab05448fa1f9f00

$ tpm2_nvdefine -x 0x1500001 -a 0x40000001 -s 32 -t 0x2000A -r -L policy.digest -P <OWNER_PW>
$ tpm2_nvlist1 NV indexes defined.

  0. NV Index: 0x1500001
  {
	Hash algorithm(nameAlg):11
 	The Index attributes(attributes):0xa0002
 	The size of the data area(dataSize):32
 	Authorization Policy for R/W/D: BC3DAED93DA82EE5BB91193878CD9699659F6786FDF039722AB05448FA1F9F00
  }

$ tpm2_nvwrite -x 0x1500001 -a 0x40000001 -f /tmp/secret.bin -P <OWNER_PW>
24 51 6b eb 6a 0a 9a c1 36 68 57 b6 64 35 51 3d 90 28 17 38 3f cb ae 7b b3 e2 df ed 7c e8 b7 99

$ tpm2_nvread -x 0x1500001 -a 0x40000001 -s 32 -o 0 -P <OWNER_PW>

The size of data:32
 24  51  6b  eb  6a  0a  9a  c1  36  68  57  b6  64  35  51  3d  90  28  17  38  3f  cb  ae  7b  b3  e2  df  ed  7c  e8  b7  99

# I can still read the secret from the TPM! ^^^
```

Shouldn't the policy prevent me from reading the "secret" value stored in NV area with index 1 because the policy is not met? (i.e. PCR 09's value is not the random one I put in `pcr_rand.bin` ?) :thinking: Is this a bug or am I simply misunderstanding the tools?

Thank you very much for your time!

PS. I also tried `tpm2_nvdefine` with different index attributes, `-t 0x2` and `-t 0x80002` (based on the TPM2.0 spec). In these cases, I'm getting the following error even when the PCR 09 based policy is met:

```bash
$ tpm2_nvread -x 0x1500001 -a 0x40000001 -s 32 -o 0 -P <OWNER_PW>
ERROR: Failed to read NVRAM area at index 0x1500001 (22020097). Error:0x149

$ tpm2_rc_decode 0x149
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 0 error code
  hex: 0x49
  name: TPM_RC_NV_AUTHORIZATION
  description: NV access authorization fails in command actions (this failure does not affect lockout.action)
```

**Comment by martinezjavier** [comment]
@spmaniato I don't think you can use PCR policy sessions for authentication with the current tpm2_nv{read,write} tools, @idesai has been working on this in PR #334. But it's tricky because when using a RM, the TPM context is flushed after each command exits so the sessions are not loaded anymore

There's currently a discussion at issue #313 on how to handle this for the tpm2_unseal command, but the same also apply to your use case AFAICT.

**Comment by williamcroberts** [comment]
@spmaniato I't looks like your attributes are wrong. You want to set up attributes:
TPMA_NV_POLICYREAD
TPMA_NV_POLICYWRITE
TPMA_NV_POLICY_DELETE

You likely want to keep the OWNERREAD|WRITE|DELETE values.

Since https://github.com/01org/tpm2.0-tools/pull/363, we have support for nice names for attributes. I think you want to specify:
```
-t policyread|policywrite
```
**Note that TPMA_NV_POLICY_DELETE aka "policydelete" is dangerous, make sure you don't lock a value to your tpm that you cannot delete! This is why I left it out.**

Take a look at section 13.4 and Table 204 for some of the details: https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-2-Structures-01.38.pdf

With that said, it should fail for both cases. We don't have the ability to carry on an authorization session with the TPM when using a resource manager (RM). The RM will flush the tpm when the tool exits, and thus you'll loose your session. You will have to use the raw /dev/tpm0 interface, and manually manage the tpm until 1 of 2 things:
1. PCR policy support is in nvread/write (in-progress)
2. the tpm_shell branch (experimental) comes to fruition: https://github.com/williamcroberts/tpm2.0-tools/tree/tpm-shell

**Comment by williamcroberts** [comment]
I think some of the reason is a misunderstanding of the spec, maybe #580 will clarify parts of it.

I need to look at how to satisfy a PCR policy with an nv index and add support for nvread/write. Hopefully more coming this week.

**Comment by paherbst** [comment]
Has this been fixed?  What is the proper way to perform these actions now?
