### ISSUE TITLE
tpm2_evictcontrol make it smarter

### ISSUE THREAD

**Issue by williamcroberts** [01org/tpm2-tools#492]
tpm2_evitccontrol, as mentioned in #488, requires the -S and -H options to be specified and identical when evicting a persistent object. Can we smarten the tool up to avoid this?

**Comment by martinezjavier** [comment]
@williamcroberts indeed, sometimes it feels as if the tools are just CLI wrappers of the TCG spec, since there's a lot of abstraction leakage and assumptions that the user is familiar with it.

I can think of two options to make the tool smarter:

1. Have a -e, --evict and -p, --persist options so the user explicitly says the operation that wants. For the former only a -H is required (and both object and persistent handlers are set to this) and for the latter both -H and -S must be specified.

In this case though I wonder if we would want to rename the tool to something like tpm2_objctrl since is not only about evicting a persistent object but also about making a transient object persistent.

2. Assume that the default option is to evict (the tool is called tpm2_evictcontrol anyways) and so with only getting a -H option, assume that the handle is for a persistent object and that the user wants to evict. And with both are passed, assume that -H is a handle for a transient object and that's why the user is providing a -S handle to assign to the persisted object.

**Comment by martinezjavier** [comment]
@williamcroberts in "Table 27 — Definition of (UINT8) TPM_HT Constants <S>" o the "Trusted Platform Module Library Part 2: Structures" document, there's a list of TPM_HT (Handle Types) constants.

TPM_HT_TRANSIENT is 0x80 and TPM_HT_PERSISTENT is 0x81. That means that the tool can just check the first byte of the 32 bits handle and check if is a transient or a persistent one and not expect a second argument for the latter.

**Comment by williamcroberts** [comment]
I like when the tools are named after their major command that they execute, it gives some coordination with the spec.

I don’t want users to be like, I read the spec, and I need to get command evictcontrol to do something, what tpm2-tool command is it.

With that said, I don't want the tools to be so Spartan they are not friendly and difficult to use. I'd like to have sane defaults, clean up
output handling and reduce option count.

I'm also ok with combining command calls when it makes sense, like readpublic....

**Comment by martinezjavier** [comment]
@williamcroberts agreed, I think we are on the same page.
