### ISSUE TITLE
** INFO: on_name_lost: com.intel.tss2.Tabrmd

### ISSUE THREAD

**Issue by slashwu** [01org/tpm2-tools#527]
Hi,
I get hard time on launching the 'tpm2-abrmd', by exporting the 'G_MESSAGES_DEBUG=all', I see the following unexpected msgs:
** INFO: on_bus_acquired: com.intel.tss2.Tabrmd
** INFO: on_name_lost: com.intel.tss2.Tabrmd
** INFO: main_loop_quit
** INFO: g_main_loop_run done, cleaning up
It looks like I'm getting issue on dbus name ? Is there anyone know what's going on ?
Thanks.

**Comment by martinezjavier** [comment]
@slashwu Did you install it from a distro package or built it from source?

The "INFO: on_name_lost: com.intel.tss2.Tabrmd" message says that the tpm2-abrmd was not able to acquired the com.intel.tss2.Tabrmd name.

This seems to be an access control issue since the system bus is usually quite restricted. So you need to add a bus configuration snippet for tpm2-abrmd so D-Bus allows the application to acquire a name in the system bus, send and receive messages, etc.

You can find this configuration in the source at ./dist/tpm2-abrmd.conf. Just copying that file to /etc/dbus-1/system.d/ (or whatever dbuspolicydir path is in your distro) should be enough.

But you should really install it though, that way tpm2-tools can be build with tabrmd TCTI support (without special configure flags).

**Comment by williamcroberts** [comment]
You should take this up on: https://github.com/01org/tpm2-abrmd

Likely send an email to the mailing list first until you know it's a bug:
https://lists.01.org/mailman/listinfo/tpm2

Likely has something to do with dbus config as @martinezjavier pointed out.

**Comment by flihp** [comment]
It's always a dbus config thing.

**Comment by flihp** [comment]
I've created a ticket in the tabrmd tracker (https://github.com/01org/tpm2-abrmd/issues/189) to get better error messages when the daemon isn't able to acquire the name on the DBus. Unfortunately this isn't as simple as checking a return code but instead requires tracking state to see whether or not the name was successfully acquired before it's lost :(
